spring:
  datasource:
    name: root
    password: root
    url: jdbc:mysql//localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver